BUSINESS_GLOSSARY = {
    "revenue": {
        "term": "Revenue",
        "definition": (
            "Revenue represents the value of successfully completed "
            "and paid customer orders. Cancelled orders are excluded."
        ),
        "synonyms": [
            "sales",
            "sales revenue",
            "total sales",
            "earnings",
        ],
        "related_tables": [
            "orders",
            "order_items",
            "payments",
        ],
        "related_columns": [
            "orders.total_amount",
            "orders.order_status",
            "order_items.line_total",
            "payments.payment_status",
        ],
        "business_rule": (
            "Revenue should exclude cancelled orders and should only "
            "include successfully paid orders."
        ),
    },

    "orders": {
        "term": "Orders",
        "definition": (
            "An order represents a customer purchase transaction "
            "containing one or more products."
        ),
        "synonyms": [
            "purchases",
            "transactions",
            "customer orders",
        ],
        "related_tables": [
            "orders",
            "order_items",
            "customers",
        ],
        "related_columns": [
            "orders.order_id",
            "orders.customer_id",
            "orders.order_status",
            "orders.order_date",
        ],
        "business_rule": (
            "An order may contain multiple order items and may have "
            "multiple payment attempts."
        ),
    },

    "average_order_value": {
        "term": "Average Order Value",
        "definition": (
            "Average Order Value represents the average monetary value "
            "of customer orders."
        ),
        "synonyms": [
            "AOV",
            "average purchase value",
            "average order amount",
        ],
        "related_tables": [
            "orders",
        ],
        "related_columns": [
            "orders.total_amount",
            "orders.order_status",
        ],
        "business_rule": (
            "Calculate using qualifying orders only and exclude "
            "cancelled orders."
        ),
    },

    "units_sold": {
        "term": "Units Sold",
        "definition": (
            "Units Sold represents the total quantity of products "
            "purchased through qualifying orders."
        ),
        "synonyms": [
            "units purchased",
            "quantity sold",
            "items sold",
        ],
        "related_tables": [
            "order_items",
            "orders",
        ],
        "related_columns": [
            "order_items.quantity",
            "order_items.order_id",
        ],
        "business_rule": (
            "Units sold should be calculated from qualifying orders "
            "and should exclude cancelled orders."
        ),
    },

    "product_revenue": {
        "term": "Product Revenue",
        "definition": (
            "Product Revenue represents the revenue generated by "
            "individual products through customer orders."
        ),
        "synonyms": [
            "product sales",
            "sales by product",
            "product-level revenue",
        ],
        "related_tables": [
            "products",
            "order_items",
            "orders",
        ],
        "related_columns": [
            "products.product_id",
            "products.product_name",
            "order_items.product_id",
            "order_items.line_total",
            "orders.order_status",
        ],
        "business_rule": (
            "Product revenue should exclude cancelled orders."
        ),
    },

    "inventory_available": {
        "term": "Available Inventory",
        "definition": (
            "Available inventory represents the quantity of stock "
            "that is currently available for sale."
        ),
        "synonyms": [
            "available stock",
            "sellable inventory",
            "stock available",
        ],
        "related_tables": [
            "inventory",
            "products",
            "warehouses",
        ],
        "related_columns": [
            "inventory.quantity_on_hand",
            "inventory.quantity_reserved",
        ],
        "business_rule": (
            "Available inventory equals quantity on hand minus "
            "quantity reserved."
        ),
    },

    "customer": {
        "term": "Customer",
        "definition": (
            "A customer represents an individual who purchases "
            "products through the OmniCart platform."
        ),
        "synonyms": [
            "buyer",
            "shopper",
            "consumer",
        ],
        "related_tables": [
            "customers",
            "orders",
        ],
        "related_columns": [
            "customers.customer_id",
            "customers.first_name",
            "customers.last_name",
            "customers.email",
        ],
        "business_rule": (
            "A customer can place multiple orders."
        ),
    },

    "cancelled_order": {
        "term": "Cancelled Order",
        "definition": (
            "A cancelled order is an order whose status indicates "
            "that the customer purchase was cancelled."
        ),
        "synonyms": [
            "cancelled purchase",
            "cancelled transaction",
        ],
        "related_tables": [
            "orders",
        ],
        "related_columns": [
            "orders.order_id",
            "orders.order_status",
        ],
        "business_rule": (
            "Cancelled orders should generally be excluded from "
            "revenue and sales performance calculations."
        ),
    },
}


def get_glossary_term(term: str):
    """
    Return the glossary definition for a business term.
    """
    return BUSINESS_GLOSSARY.get(term.lower())


def get_all_glossary_terms():
    """
    Return all business glossary entries.
    """
    return BUSINESS_GLOSSARY